/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BigFileUpload: typeof import('./src/components/BigFileUpload/index.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
  }
}
